AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#S3 Parameters
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain

Resources:
  LandingS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
         Fn::Join:
          - "-"
          - [ "tpgt", !Ref DomainName, !Ref EnvType, "landing"]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256        
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  LandingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LandingS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowOnlyHttpsRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${LandingS3Bucket}"
              - !Sub "arn:aws:s3:::${LandingS3Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"      

  RawS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
         Fn::Join:
          - "-"
          - [ "tpgt", !Ref DomainName, !Ref EnvType, "raw"]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  RawBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowOnlyHttpsRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${RawS3Bucket}"
              - !Sub "arn:aws:s3:::${RawS3Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"            

  TrustedS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
         Fn::Join:
          - "-"
          - [ "tpgt", !Ref DomainName, !Ref EnvType, "trusted"]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256        
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
            
  TrustedBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrustedS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowOnlyHttpsRequests
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${TrustedS3Bucket}"
              - !Sub "arn:aws:s3:::${TrustedS3Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"                        

Outputs:
  LandingBucketName:
    Description: The name of the Landing S3 bucket
    Value: !Ref LandingS3Bucket
  RawS3BucketName:
    Description: The name of the Raw S3 bucket
    Value: !Ref RawS3Bucket
  TrustedS3BucketName:
    Description: The name of the Enriched S3 bucket
    Value: !Ref TrustedS3Bucket

