AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue Crawler Nested Stack'

Parameters:
  CrawlerName:
    Type: String
    Description: 'Name of the Glue Crawler'
  
  DatabaseName:
    Type: String
    Description: 'Name of the Glue Database to store the crawled data'
  
  S3TargetPath:
    Type: String
    Description: 'S3 path for the crawler to scan'

Resources:
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3TargetPath}'
                  - !Sub 'arn:aws:s3:::${S3TargetPath}/*'

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DatabaseName
      Targets:
        S3Targets:
          - Path: !Sub 's3://${S3TargetPath}
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"

Outputs:
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value: !Ref GlueCrawler