AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue Database CloudFormation Template'

Parameters:
  DatabaseName:
    Type: String
    Default: 'my-glue-database'
    Description: 'Name of the Glue Database'

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: "Database for storing metadata from Glue Crawler"

Outputs:
  DatabaseName:
    Description: 'Name of the created Glue Database'
    Value: !Ref GlueDatabase