AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#S3 Parameters  
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
  BucketFilePath:
    Type: String
    Description: bucket yaml path
#GlueDB Parameters
  DatabaseName:
    Type: String
    Default: 'tpg-glue-db'  
    Description: 'Name of the Glue Database'
  GlueDBPath:
    Type: String
    Description: Database yaml path    

#Crawler Parameters
  CrawlerName:
    Type: String
    Default: 'tpg-glue-crawler'
    Description: 'Name of the Glue Crawler'
  GlueCrawlerPath:
    Type: String
    Description: Crawler yaml path    

#Redshift Parameters
  WorkgroupName:
    Type: String
    Default: 'tpg-redshift-workgroup'
    Description: 'Name of the Redshift Serverless workgroup'
  NamespaceName:
    Type: String
    Default: 'tpg-redshift-namespace'    
    Description: 'Name of the Redshift Serverless namespace'
  RedshiftDatabaseName:
    Type: String
    Default: 'tpg-redshift-database'
    Description: 'Name of the initial database to be created'
  AdminUsername:
    Type: String
    Default: 'admin'
    Description: 'Admin username for the Redshift Serverless instance'
  AdminUserPassword:
    Type: String
    Default: 'Password28'
    NoEcho: true
    Description: 'Admin user password for the Redshift Serverless instance'
  BaseCapacity:
    Type: Number
    Default: 32
    Description: 'Base RPU capacity for the Redshift Serverless instance'
  RedshiftStackUrl:
    Type: String
    Description: 'S3 URL of the nested stack template'
  SubnetIds:
    Type: String
    Description: 'Subnet Ids'
    Default: subnet-0e02df7b9e58e3960,subnet-05d7a985f0bdf9b64,subnet-04fc4b2eacf4f1df4

Resources:
  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BucketFilePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueDBPath
      Parameters:
        DatabaseName: !Ref DatabaseName

  GlueCrawler:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueCrawlerPath
      Parameters:
        CrawlerName: !Ref CrawlerName
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName
        S3TargetPath: !GetAtt s3buckets.Outputs.LandingBucketName

  RedshiftStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftStackUrl
      Parameters:
        WorkgroupName: !Ref WorkgroupName
        NamespaceName: !Ref NamespaceName
        RedshiftDatabaseName: !Ref RedshiftDatabaseName
        AdminUsername: !Ref AdminUsername
        AdminUserPassword: !Ref AdminUserPassword
        BaseCapacity: !Ref BaseCapacity
        SubnetIds: !Ref SubnetIds


Outputs:
  LandingBucketName:
    Description: The name of the Landing S3 bucket
    Value: !GetAtt s3buckets.Outputs.LandingBucketName
  RawS3BucketName:
    Description: The name of the Raw S3 bucket
    Value: !GetAtt s3buckets.Outputs.RawS3BucketName
  EnrichedS3BucketName:
    Description: The name of the Enriched S3 bucket
    Value: !GetAtt s3buckets.Outputs.EnrichedS3BucketName
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value:  !GetAtt GlueDatabase.Outputs.DatabaseName
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value:  !GetAtt GlueCrawler.Outputs.CrawlerName
  NamespaceArn:
    Description: 'ARN of the Redshift Serverless Namespace'
    Value: !GetAtt RedshiftStack.Outputs.NamespaceArn
  WorkgroupArn:
    Description: 'ARN of the Redshift Serverless Workgroup'
    Value: !GetAtt RedshiftStack.Outputs.WorkgroupArn
  RedshiftServerlessRoleArn:
    Description: 'ARN of the IAM Role for Redshift Serverless'
    Value: !GetAtt RedshiftStack.Outputs.RedshiftServerlessRoleArn
  SecurityGroupId:
    Description: 'ID of the Security Group for Redshift Serverless'
    Value: !GetAtt RedshiftStack.Outputs.SecurityGroupId


