AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#S3 Parameters  
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
  BucketFilePath:
    Type: String
    Description: bucket yaml path
#GlueDB Parameters
  DatabaseName:
    Type: String
    Default: 'tpg-glue-db'  
    Description: 'Name of the Glue Database'
  DBFilePath:
    Type: String
    Description: DB yaml path    

#Crawler Parameters
  CrawlerName:
    Type: String
    Default: 'tpg-glue-crawler'
    Description: 'Name of the Glue Crawler'
  S3TargetPath:
    Type: String
    Description: 'S3 path for the crawler to scan'  
    Default: 'RawS3Bucket'
  CrawlerFilePath:
    Type: String
    Description: Cralwer yaml path 

Resources:
  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BucketFilePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      TemplateURL: !Ref DBFilePath
      Parameters:
        DatabaseName: !Ref DatabaseName

  GlueCrawler:
    Type: AWS::Glue::Database
    Properties:
      TemplateURL: !Ref CrawlerFilePath
      Parameters:
        CrawlerName: !Ref CrawlerName
        DatabaseName: !Ref DatabaseName
        S3TargetPath: !GetAtt s3buckets.Outputs.LandingBucketName

Outputs:
  LandingBucketName:
    Description: The name of the Landing S3 bucket
    Value: !GetAtt s3buckets.Outputs.LandingBucketName
  RawS3BucketName:
    Description: The name of the Raw S3 bucket
    Value: !GetAtt s3buckets.Outputs.RawS3BucketName
  EnrichedS3BucketName:
    Description: The name of the Enriched S3 bucket
    Value: !GetAtt s3buckets.Outputs.EnrichedS3BucketName
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value: !GetAtt GlueDatabase.Outputs.DatabaseName
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value: !GetAtt GlueCrawler.Outputs.CrawlerName

