AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating Amazon Redshift Serverless'

Parameters:
  WorkgroupName:
    Type: String
  NamespaceName:
    Type: String
  DatabaseName:
    Type: String
  AdminUsername:
    Type: String
  AdminUserPassword:
    Type: String
    NoEcho: true
  BaseCapacity:
    Type: Number
    Default: 32

Resources:
  RedshiftServerlessNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Ref NamespaceName
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminUserPassword
      DbName: !Ref DatabaseName
      DefaultIamRoleArn: !GetAtt RedshiftServerlessRole.Arn

  RedshiftServerlessWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: !Ref WorkgroupName
      NamespaceName: !Ref NamespaceName
      BaseCapacity: !Ref BaseCapacity
      PubliclyAccessible: false
      SecurityGroupIds: 
        - !Ref RedshiftServerlessSecurityGroup

  RedshiftServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRedshiftAllCommandsFullAccess

  RedshiftServerlessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redshift Serverless
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Adjust as needed for your security requirements

Outputs:
  NamespaceArn:
    Description: 'ARN of the Redshift Serverless Namespace'
    Value: !GetAtt RedshiftServerlessNamespace.NamespaceArn
  WorkgroupArn:
    Description: 'ARN of the Redshift Serverless Workgroup'
    Value: !GetAtt RedshiftServerlessWorkgroup.WorkgroupArn