AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating Amazon Redshift Serverless resources'

Parameters:
  WorkgroupName:
    Type: String
  NamespaceName:
    Type: String
  RedshiftDatabaseName:
    Type: String
  AdminUsername:
    Type: String
  AdminUserPassword:
    Type: String
    NoEcho: true
  BaseCapacity:
    Type: Number
    Default: 32
  SubnetIds:
    Description: Comma-separated list of subnet IDs for the Redshift Serverless workgroup
    Type: CommaDelimitedList

Resources:
  RedshiftServerlessNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Ref NamespaceName
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminUserPassword
      DbName: !Ref RedshiftDatabaseName
      DefaultIamRoleArn: !GetAtt RedshiftServerlessRole.Arn
      IamRoles: 
        - !GetAtt RedshiftServerlessRole.Arn

  RedshiftServerlessWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: !Ref WorkgroupName
      NamespaceName: !Ref NamespaceName
      BaseCapacity: !Ref BaseCapacity
      PubliclyAccessible: false
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: 
        - !Ref RedshiftServerlessSecurityGroup

  RedshiftServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift-serverless.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRedshiftAllCommandsFullAccess

  RedshiftServerlessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: 'vpc-0e22305d886064b94'
      GroupDescription: Security group for Redshift Serverless
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Note: Adjust as needed for your security requirements

Outputs:
  NamespaceArn:
    Description: 'ARN of the Redshift Serverless Namespace'
    Value: !GetAtt RedshiftServerlessNamespace.NamespaceArn
  WorkgroupArn:
    Description: 'ARN of the Redshift Serverless Workgroup'
    Value: !GetAtt RedshiftServerlessWorkgroup.WorkgroupArn
  RedshiftServerlessRoleArn:
    Description: 'ARN of the IAM Role for Redshift Serverless'
    Value: !GetAtt RedshiftServerlessRole.Arn
  SecurityGroupId:
    Description: 'ID of the Security Group for Redshift Serverless'
    Value: !Ref RedshiftServerlessSecurityGroup
