# redshift-nested.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating Amazon Redshift cluster'

Parameters:
  ClusterIdentifier:
    Type: String
    Description: 'The identifier of the cluster'
  
  DatabaseName:
    Type: String
    Description: 'The name of the first database to be created when the cluster is created'
  
  MasterUsername:
    Type: String
    Description: 'The user name associated with the master user account for the cluster'
  
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: 'The password associated with the master user account for the cluster'
  
  NodeType:
    Type: String
    Default: dc2.large
    Description: 'The node type to be provisioned for the cluster'
  
  NumberOfNodes:
    Type: Number
    Default: 1
    Description: 'The number of compute nodes in the cluster'
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC ID where the cluster will be created'
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'The list of VPC subnet IDs for the cluster'

Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: !Ref ClusterIdentifier
      DBName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: !Ref NodeType
      NumberOfNodes: !Ref NumberOfNodes
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup
      VpcSecurityGroupIds: 
        - !Ref RedshiftSecurityGroup
      PubliclyAccessible: false
      Port: 5439

  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Subnet group for Redshift cluster
      SubnetIds: !Ref SubnetIds

  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redshift cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Note: Adjust this for your security requirements

Outputs:
  ClusterEndpoint:
    Description: 'Endpoint of the Redshift cluster'
    Value: !GetAtt RedshiftCluster.Endpoint.Address
  ClusterPort:
    Description: 'Port of the Redshift cluster'
    Value: !GetAtt RedshiftCluster.Endpoint.Port
